name: First run of fetch data from VariableSpeedLimit endpoint

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  fetch-data:
    name: Fetch data first run
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      #- name: Download previous artifact data
      #  uses: actions/download-artifact@v5
      #  with:
      #    name: variable-speed-limits
      #    path: VariableSpeedLimits.txt
          
      - name: Start
        run: echo Fetch started

      - name: Download data file
        run: |
          curl -L -o variable_speed_limit.json https://m.jidelnivozy.cz

      - name: Run curl
        run: |
          curl --verbose 'https://api.dopravniinfo.cz/VariableSpeedLimit.ashx' \
            -X 'GET' \
            -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' \
            -H 'Sec-Fetch-Site: same-origin' \
            -H 'Cookie: sessid=rs1|aRIx7; ADC_CONN_539B3595F4E=865A5B39C0889CE30E6B24265B5B3B78C881C52944143FAA5C72287B81CDAD97732BB38EFF59B74E; ADC_REQ_2E94AF76E7=217F82240CA2BCB9BE14566D34099C908BF8FC3F82199C849C195141F1C9FE61ADC02FEEACC3BFE0' \
            -H 'Sec-Fetch-Mode: navigate' \
            -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1.1 Safari/605.1.15' \
            -H 'Accept-Language: cs-CZ,cs;q=0.9' \
            -H 'Accept-Encoding: gzip, deflate, br' \
            -H 'Sec-Fetch-Dest: document' \
            -H 'Priority: u=0, i'

      - name: Run jq
        run: jq --raw-output '.VariableSpeedLimitData[].VariableSpeedLimitSectionList[] | .Time = (now | todateiso8601) | [ .Time, .Name, .Direction, .LimitType // "130" ] | @csv' >> VariableSpeedLimits.txt
          
      - name: Fetch succeeded
        run: echo Fetch succeeded
        
      - name: Upload fresh artifact data
        uses: actions/upload-artifact@v4
        with:
          name: variable-speed-limits
          path: VariableSpeedLimits.txt

        
