# This is a basic workflow to help you get started with Actions

name: Fetch data from VariableSpeedLimit endpoint

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  fetch-data:
    name: Fetch data
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- uses: actions/checkout@v4

      #- name: Download previous artifact data
      #  uses: actions/download-artifact@v5
      #  with:
      #    name: variable-speed-limits
      #    path: VariableSpeedLimits.txt
          
      - name: Fetch data from endpoint
        run: |
          curl -s https://api.dopravniinfo.cz/VariableSpeedLimit.ashx | jq --raw-output '.VariableSpeedLimitData[].VariableSpeedLimitSectionList[] | .Time = (now | todateiso8601) | [ .Time, .Name, .Direction, .LimitType // "130" ] | @csv' >> VariableSpeedLimits.txt
          echo Fetch succeeded
          
      - name: Upload fresh artifact data
        uses: actions/upload-artifact@v4
        with:
          name: variable-speed-limits
          path: VariableSpeedLimits.txt

        
